### PR TITLE
Add volume for mediawiki images

### PR DESCRIPTION
**Pull request by addshore**
Thoughts?

### CODE REVIEW

**Comment by davidbarratt** [comment]
I mean the docker compose is just a bare-minimum example. I don't expect anyone to use it that way.

**Comment by davidbarratt** [comment]
I added your suggested as a comment in `docker-compose.yml` if you want it in yours I would just add a `docker-compose.override.yml` :)

**Comment by addshore** [comment]
@davidbarratt if you don't think that this should be in there then you should also remove the database volume.
All this does is bring the images dir to the same level or persistence as the db.
With only one or the other having a volume the example compose can result in confusing people IMO when their db remains but their images have vanished for some reason.

**Comment by davidbarratt** [comment]
@addshore I would love to remove the database volume! But sadly you cannot remove volumes from `docker-compose`. Since the `mariadb` image has already added the volume:
https://github.com/docker-library/mariadb/blob/198f04b24ca6f668357106355b03d38d1f3234bc/10.2/Dockerfile#L99
Docker will create the volume everytime you start the container unless you give the volume a name which is what the directive in the example `docker-compose.yml` does.

I took a look at some of the other official images and I noticed that none of them have `docker-compose.yml` files, so I removed the one in this repo.

**Pull request closed without merging**
